<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = array(
            array('id' => '1','country' => 'Afghanistan','currency' => 'Afghani','code' => 'AFN','symbol' => '؋'),
            array('id' => '2','country' => 'Åland Islands','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '3','country' => 'Albania','currency' => 'Lek','code' => 'ALL','symbol' => 'Lek'),
            array('id' => '4','country' => 'Algeria','currency' => 'Algerian Dinar','code' => 'DZD','symbol' => NULL),
            array('id' => '5','country' => 'American Samoa','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '6','country' => 'Andorra','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '7','country' => 'Angola','currency' => 'Kwanza','code' => 'AOA','symbol' => NULL),
            array('id' => '8','country' => 'Anguilla','currency' => 'East Caribbean Dollar','code' => 'XCD','symbol' => NULL),
            array('id' => '9','country' => 'Antigua And Barbuda','currency' => 'East Caribbean Dollar','code' => 'XCD','symbol' => NULL),
            array('id' => '10','country' => 'Argentina','currency' => 'Argentine Peso','code' => 'ARS','symbol' => '$'),
            array('id' => '11','country' => 'Armenia','currency' => 'Armenian Dram','code' => 'AMD','symbol' => NULL),
            array('id' => '12','country' => 'Aruba','currency' => 'Aruban Florin','code' => 'AWG','symbol' => NULL),
            array('id' => '13','country' => 'Australia','currency' => 'Australian Dollar','code' => 'AUD','symbol' => '$'),
            array('id' => '14','country' => 'Austria','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '15','country' => 'Azerbaijan','currency' => 'Azerbaijan Manat','code' => 'AZN','symbol' => NULL),
            array('id' => '16','country' => 'Bahamas','currency' => 'Bahamian Dollar','code' => 'BSD','symbol' => '$'),
            array('id' => '17','country' => 'Bahrain','currency' => 'Bahraini Dinar','code' => 'BHD','symbol' => NULL),
            array('id' => '18','country' => 'Bangladesh','currency' => 'Taka','code' => 'BDT','symbol' => '৳'),
            array('id' => '19','country' => 'Barbados','currency' => 'Barbados Dollar','code' => 'BBD','symbol' => '$'),
            array('id' => '20','country' => 'Belarus','currency' => 'Belarusian Ruble','code' => 'BYN','symbol' => NULL),
            array('id' => '21','country' => 'Belgium','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '22','country' => 'Belize','currency' => 'Belize Dollar','code' => 'BZD','symbol' => 'BZ$'),
            array('id' => '23','country' => 'Benin','currency' => 'CFA Franc BCEAO','code' => 'XOF','symbol' => NULL),
            array('id' => '24','country' => 'Bermuda','currency' => 'Bermudian Dollar','code' => 'BMD','symbol' => NULL),
            array('id' => '25','country' => 'Bhutan','currency' => 'Indian Rupee','code' => 'INR','symbol' => '₹'),
            array('id' => '26','country' => 'Bhutan','currency' => 'Ngultrum','code' => 'BTN','symbol' => NULL),
            array('id' => '27','country' => 'Bolivia','currency' => 'Boliviano','code' => 'BOB','symbol' => NULL),
            array('id' => '28','country' => 'Bolivia','currency' => 'Mvdol','code' => 'BOV','symbol' => NULL),
            array('id' => '29','country' => 'Bonaire, Sint Eustatius And Saba','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '30','country' => 'Bosnia And Herzegovina','currency' => 'Convertible Mark','code' => 'BAM','symbol' => NULL),
            array('id' => '31','country' => 'Botswana','currency' => 'Pula','code' => 'BWP','symbol' => NULL),
            array('id' => '32','country' => 'Bouvet Island','currency' => 'Norwegian Krone','code' => 'NOK','symbol' => NULL),
            array('id' => '33','country' => 'Brazil','currency' => 'Brazilian Real','code' => 'BRL','symbol' => 'R$'),
            array('id' => '34','country' => 'British Indian Ocean Territory','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '35','country' => 'Brunei Darussalam','currency' => 'Brunei Dollar','code' => 'BND','symbol' => NULL),
            array('id' => '36','country' => 'Bulgaria','currency' => 'Bulgarian Lev','code' => 'BGN','symbol' => 'лв'),
            array('id' => '37','country' => 'Burkina Faso','currency' => 'CFA Franc BCEAO','code' => 'XOF','symbol' => NULL),
            array('id' => '38','country' => 'Burundi','currency' => 'Burundi Franc','code' => 'BIF','symbol' => NULL),
            array('id' => '39','country' => 'Cabo Verde','currency' => 'Cabo Verde Escudo','code' => 'CVE','symbol' => NULL),
            array('id' => '40','country' => 'Cambodia','currency' => 'Riel','code' => 'KHR','symbol' => '៛'),
            array('id' => '41','country' => 'Cameroon','currency' => 'CFA Franc BEAC','code' => 'XAF','symbol' => NULL),
            array('id' => '42','country' => 'Canada','currency' => 'Canadian Dollar','code' => 'CAD','symbol' => '$'),
            array('id' => '43','country' => 'Cayman Islands','currency' => 'Cayman Islands Dollar','code' => 'KYD','symbol' => NULL),
            array('id' => '44','country' => 'Central African Republic','currency' => 'CFA Franc BEAC','code' => 'XAF','symbol' => NULL),
            array('id' => '45','country' => 'Chad','currency' => 'CFA Franc BEAC','code' => 'XAF','symbol' => NULL),
            array('id' => '46','country' => 'Chile','currency' => 'Chilean Peso','code' => 'CLP','symbol' => '$'),
            array('id' => '47','country' => 'Chile','currency' => 'Unidad de Fomento','code' => 'CLF','symbol' => NULL),
            array('id' => '48','country' => 'China','currency' => 'Yuan Renminbi','code' => 'CNY','symbol' => '¥'),
            array('id' => '49','country' => 'Christmas Island','currency' => 'Australian Dollar','code' => 'AUD','symbol' => NULL),
            array('id' => '50','country' => 'Cocos (keeling) Islands','currency' => 'Australian Dollar','code' => 'AUD','symbol' => NULL),
            array('id' => '51','country' => 'Colombia','currency' => 'Colombian Peso','code' => 'COP','symbol' => '$'),
            array('id' => '52','country' => 'Colombia','currency' => 'Unidad de Valor Real','code' => 'COU','symbol' => NULL),
            array('id' => '53','country' => 'Comoros','currency' => 'Comorian Franc ','code' => 'KMF','symbol' => NULL),
            array('id' => '54','country' => 'Congo (the Democratic Republic Of The)','currency' => 'Congolese Franc','code' => 'CDF','symbol' => NULL),
            array('id' => '55','country' => 'Congo','currency' => 'CFA Franc BEAC','code' => 'XAF','symbol' => NULL),
            array('id' => '56','country' => 'Cook Islands','currency' => 'New Zealand Dollar','code' => 'NZD','symbol' => '$'),
            array('id' => '57','country' => 'Costa Rica','currency' => 'Costa Rican Colon','code' => 'CRC','symbol' => NULL),
            array('id' => '58','country' => 'Côte D\'ivoire','currency' => 'CFA Franc BCEAO','code' => 'XOF','symbol' => NULL),
            array('id' => '59','country' => 'Croatia','currency' => 'Kuna','code' => 'HRK','symbol' => 'kn'),
            array('id' => '60','country' => 'Cuba','currency' => 'Cuban Peso','code' => 'CUP','symbol' => NULL),
            array('id' => '61','country' => 'Cuba','currency' => 'Peso Convertible','code' => 'CUC','symbol' => NULL),
            array('id' => '62','country' => 'Curaçao','currency' => 'Netherlands Antillean Guilder','code' => 'ANG','symbol' => NULL),
            array('id' => '63','country' => 'Cyprus','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '64','country' => 'Czechia','currency' => 'Czech Koruna','code' => 'CZK','symbol' => 'Kč'),
            array('id' => '65','country' => 'Denmark','currency' => 'Danish Krone','code' => 'DKK','symbol' => 'kr'),
            array('id' => '66','country' => 'Djibouti','currency' => 'Djibouti Franc','code' => 'DJF','symbol' => NULL),
            array('id' => '67','country' => 'Dominica','currency' => 'East Caribbean Dollar','code' => 'XCD','symbol' => NULL),
            array('id' => '68','country' => 'Dominican Republic','currency' => 'Dominican Peso','code' => 'DOP','symbol' => NULL),
            array('id' => '69','country' => 'Ecuador','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '70','country' => 'Egypt','currency' => 'Egyptian Pound','code' => 'EGP','symbol' => NULL),
            array('id' => '71','country' => 'El Salvador','currency' => 'El Salvador Colon','code' => 'SVC','symbol' => NULL),
            array('id' => '72','country' => 'El Salvador','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '73','country' => 'Equatorial Guinea','currency' => 'CFA Franc BEAC','code' => 'XAF','symbol' => NULL),
            array('id' => '74','country' => 'Eritrea','currency' => 'Nakfa','code' => 'ERN','symbol' => NULL),
            array('id' => '75','country' => 'Estonia','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '76','country' => 'Eswatini','currency' => 'Lilangeni','code' => 'SZL','symbol' => NULL),
            array('id' => '77','country' => 'Ethiopia','currency' => 'Ethiopian Birr','code' => 'ETB','symbol' => NULL),
            array('id' => '78','country' => 'European Union','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '79','country' => 'Falkland Islands [Malvinas]','currency' => 'Falkland Islands Pound','code' => 'FKP','symbol' => NULL),
            array('id' => '80','country' => 'Faroe Islands','currency' => 'Danish Krone','code' => 'DKK','symbol' => NULL),
            array('id' => '81','country' => 'Fiji','currency' => 'Fiji Dollar','code' => 'FJD','symbol' => NULL),
            array('id' => '82','country' => 'Finland','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '83','country' => 'France','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '84','country' => 'French Guiana','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '85','country' => 'French Polynesia','currency' => 'CFP Franc','code' => 'XPF','symbol' => NULL),
            array('id' => '86','country' => 'French Southern Territories','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '87','country' => 'Gabon','currency' => 'CFA Franc BEAC','code' => 'XAF','symbol' => NULL),
            array('id' => '88','country' => 'Gambia','currency' => 'Dalasi','code' => 'GMD','symbol' => NULL),
            array('id' => '89','country' => 'Georgia','currency' => 'Lari','code' => 'GEL','symbol' => '₾'),
            array('id' => '90','country' => 'Germany','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '91','country' => 'Ghana','currency' => 'Ghana Cedi','code' => 'GHS','symbol' => NULL),
            array('id' => '92','country' => 'Gibraltar','currency' => 'Gibraltar Pound','code' => 'GIP','symbol' => NULL),
            array('id' => '93','country' => 'Greece','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '94','country' => 'Greenland','currency' => 'Danish Krone','code' => 'DKK','symbol' => NULL),
            array('id' => '95','country' => 'Grenada','currency' => 'East Caribbean Dollar','code' => 'XCD','symbol' => NULL),
            array('id' => '96','country' => 'Guadeloupe','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '97','country' => 'Guam','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '98','country' => 'Guatemala','currency' => 'Quetzal','code' => 'GTQ','symbol' => NULL),
            array('id' => '99','country' => 'Guernsey','currency' => 'Pound Sterling','code' => 'GBP','symbol' => '£'),
            array('id' => '100','country' => 'Guinea','currency' => 'Guinean Franc','code' => 'GNF','symbol' => NULL),
            array('id' => '101','country' => 'Guinea-bissau','currency' => 'CFA Franc BCEAO','code' => 'XOF','symbol' => NULL),
            array('id' => '102','country' => 'Guyana','currency' => 'Guyana Dollar','code' => 'GYD','symbol' => NULL),
            array('id' => '103','country' => 'Haiti','currency' => 'Gourde','code' => 'HTG','symbol' => NULL),
            array('id' => '104','country' => 'Haiti','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '105','country' => 'Heard Island And Mcdonald Islands','currency' => 'Australian Dollar','code' => 'AUD','symbol' => NULL),
            array('id' => '106','country' => 'Holy See (Vatican)','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '107','country' => 'Honduras','currency' => 'Lempira','code' => 'HNL','symbol' => NULL),
            array('id' => '108','country' => 'Hong Kong','currency' => 'Hong Kong Dollar','code' => 'HKD','symbol' => '$'),
            array('id' => '109','country' => 'Hungary','currency' => 'Forint','code' => 'HUF','symbol' => 'ft'),
            array('id' => '110','country' => 'Iceland','currency' => 'Iceland Krona','code' => 'ISK','symbol' => NULL),
            array('id' => '111','country' => 'India','currency' => 'Indian Rupee','code' => 'INR','symbol' => '₹'),
            array('id' => '112','country' => 'Indonesia','currency' => 'Rupiah','code' => 'IDR','symbol' => 'Rp'),
            array('id' => '113','country' => 'International Monetary Fund (IMF)','currency' => 'SDR (Special Drawing Right)','code' => 'XDR','symbol' => NULL),
            array('id' => '114','country' => 'Iran','currency' => 'Iranian Rial','code' => 'IRR','symbol' => NULL),
            array('id' => '115','country' => 'Iraq','currency' => 'Iraqi Dinar','code' => 'IQD','symbol' => NULL),
            array('id' => '116','country' => 'Ireland','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '117','country' => 'Isle Of Man','currency' => 'Pound Sterling','code' => 'GBP','symbol' => '£'),
            array('id' => '118','country' => 'Israel','currency' => 'New Israeli Sheqel','code' => 'ILS','symbol' => '₪'),
            array('id' => '119','country' => 'Italy','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '120','country' => 'Jamaica','currency' => 'Jamaican Dollar','code' => 'JMD','symbol' => NULL),
            array('id' => '121','country' => 'Japan','currency' => 'Yen','code' => 'JPY','symbol' => '¥'),
            array('id' => '122','country' => 'Jersey','currency' => 'Pound Sterling','code' => 'GBP','symbol' => '£'),
            array('id' => '123','country' => 'Jordan','currency' => 'Jordanian Dinar','code' => 'JOD','symbol' => NULL),
            array('id' => '124','country' => 'Kazakhstan','currency' => 'Tenge','code' => 'KZT','symbol' => NULL),
            array('id' => '125','country' => 'Kenya','currency' => 'Kenyan Shilling','code' => 'KES','symbol' => 'Ksh'),
            array('id' => '126','country' => 'Kiribati','currency' => 'Australian Dollar','code' => 'AUD','symbol' => NULL),
            array('id' => '127','country' => 'Korea (the Democratic People’s Republic Of)','currency' => 'North Korean Won','code' => 'KPW','symbol' => NULL),
            array('id' => '128','country' => 'Korea (the Republic Of)','currency' => 'Won','code' => 'KRW','symbol' => '₩'),
            array('id' => '129','country' => 'Kuwait','currency' => 'Kuwaiti Dinar','code' => 'KWD','symbol' => NULL),
            array('id' => '130','country' => 'Kyrgyzstan','currency' => 'Som','code' => 'KGS','symbol' => NULL),
            array('id' => '131','country' => 'Lao People’s Democratic Republic','currency' => 'Lao Kip','code' => 'LAK','symbol' => NULL),
            array('id' => '132','country' => 'Latvia','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '133','country' => 'Lebanon','currency' => 'Lebanese Pound','code' => 'LBP','symbol' => NULL),
            array('id' => '134','country' => 'Lesotho','currency' => 'Loti','code' => 'LSL','symbol' => NULL),
            array('id' => '135','country' => 'Lesotho','currency' => 'Rand','code' => 'ZAR','symbol' => NULL),
            array('id' => '136','country' => 'Liberia','currency' => 'Liberian Dollar','code' => 'LRD','symbol' => NULL),
            array('id' => '137','country' => 'Libya','currency' => 'Libyan Dinar','code' => 'LYD','symbol' => NULL),
            array('id' => '138','country' => 'Liechtenstein','currency' => 'Swiss Franc','code' => 'CHF','symbol' => NULL),
            array('id' => '139','country' => 'Lithuania','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '140','country' => 'Luxembourg','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '141','country' => 'Macao','currency' => 'Pataca','code' => 'MOP','symbol' => NULL),
            array('id' => '142','country' => 'North Macedonia','currency' => 'Denar','code' => 'MKD','symbol' => NULL),
            array('id' => '143','country' => 'Madagascar','currency' => 'Malagasy Ariary','code' => 'MGA','symbol' => NULL),
            array('id' => '144','country' => 'Malawi','currency' => 'Malawi Kwacha','code' => 'MWK','symbol' => NULL),
            array('id' => '145','country' => 'Malaysia','currency' => 'Malaysian Ringgit','code' => 'MYR','symbol' => 'RM'),
            array('id' => '146','country' => 'Maldives','currency' => 'Rufiyaa','code' => 'MVR','symbol' => NULL),
            array('id' => '147','country' => 'Mali','currency' => 'CFA Franc BCEAO','code' => 'XOF','symbol' => NULL),
            array('id' => '148','country' => 'Malta','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '149','country' => 'Marshall Islands','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '150','country' => 'Martinique','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '151','country' => 'Mauritania','currency' => 'Ouguiya','code' => 'MRU','symbol' => NULL),
            array('id' => '152','country' => 'Mauritius','currency' => 'Mauritius Rupee','code' => 'MUR','symbol' => NULL),
            array('id' => '153','country' => 'Mayotte','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '154','country' => 'Member Countries Of The African Development Bank Group','currency' => 'ADB Unit of Account','code' => 'XUA','symbol' => NULL),
            array('id' => '155','country' => 'Mexico','currency' => 'Mexican Peso','code' => 'MXN','symbol' => '$'),
            array('id' => '156','country' => 'Mexico','currency' => 'Mexican Unidad de Inversion (UDI)','code' => 'MXV','symbol' => NULL),
            array('id' => '157','country' => 'Micronesia','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '158','country' => 'Moldova','currency' => 'Moldovan Leu','code' => 'MDL','symbol' => NULL),
            array('id' => '159','country' => 'Monaco','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '160','country' => 'Mongolia','currency' => 'Tugrik','code' => 'MNT','symbol' => NULL),
            array('id' => '161','country' => 'Montenegro','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '162','country' => 'Montserrat','currency' => 'East Caribbean Dollar','code' => 'XCD','symbol' => NULL),
            array('id' => '163','country' => 'Morocco','currency' => 'Moroccan Dirham','code' => 'MAD','symbol' => ' .د.م '),
            array('id' => '164','country' => 'Mozambique','currency' => 'Mozambique Metical','code' => 'MZN','symbol' => NULL),
            array('id' => '165','country' => 'Myanmar','currency' => 'Kyat','code' => 'MMK','symbol' => NULL),
            array('id' => '166','country' => 'Namibia','currency' => 'Namibia Dollar','code' => 'NAD','symbol' => NULL),
            array('id' => '167','country' => 'Namibia','currency' => 'Rand','code' => 'ZAR','symbol' => NULL),
            array('id' => '168','country' => 'Nauru','currency' => 'Australian Dollar','code' => 'AUD','symbol' => NULL),
            array('id' => '169','country' => 'Nepal','currency' => 'Nepalese Rupee','code' => 'NPR','symbol' => NULL),
            array('id' => '170','country' => 'Netherlands','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '171','country' => 'New Caledonia','currency' => 'CFP Franc','code' => 'XPF','symbol' => NULL),
            array('id' => '172','country' => 'New Zealand','currency' => 'New Zealand Dollar','code' => 'NZD','symbol' => '$'),
            array('id' => '173','country' => 'Nicaragua','currency' => 'Cordoba Oro','code' => 'NIO','symbol' => NULL),
            array('id' => '174','country' => 'Niger','currency' => 'CFA Franc BCEAO','code' => 'XOF','symbol' => NULL),
            array('id' => '175','country' => 'Nigeria','currency' => 'Naira','code' => 'NGN','symbol' => '₦'),
            array('id' => '176','country' => 'Niue','currency' => 'New Zealand Dollar','code' => 'NZD','symbol' => '$'),
            array('id' => '177','country' => 'Norfolk Island','currency' => 'Australian Dollar','code' => 'AUD','symbol' => NULL),
            array('id' => '178','country' => 'Northern Mariana Islands','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '179','country' => 'Norway','currency' => 'Norwegian Krone','code' => 'NOK','symbol' => 'kr'),
            array('id' => '180','country' => 'Oman','currency' => 'Rial Omani','code' => 'OMR','symbol' => NULL),
            array('id' => '181','country' => 'Pakistan','currency' => 'Pakistan Rupee','code' => 'PKR','symbol' => 'Rs'),
            array('id' => '182','country' => 'Palau','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '183','country' => 'Panama','currency' => 'Balboa','code' => 'PAB','symbol' => NULL),
            array('id' => '184','country' => 'Panama','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '185','country' => 'Papua New Guinea','currency' => 'Kina','code' => 'PGK','symbol' => NULL),
            array('id' => '186','country' => 'Paraguay','currency' => 'Guarani','code' => 'PYG','symbol' => NULL),
            array('id' => '187','country' => 'Peru','currency' => 'Sol','code' => 'PEN','symbol' => 'S'),
            array('id' => '188','country' => 'Philippines','currency' => 'Philippine Peso','code' => 'PHP','symbol' => '₱'),
            array('id' => '189','country' => 'Pitcairn','currency' => 'New Zealand Dollar','code' => 'NZD','symbol' => '$'),
            array('id' => '190','country' => 'Poland','currency' => 'Zloty','code' => 'PLN','symbol' => 'zł'),
            array('id' => '191','country' => 'Portugal','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '192','country' => 'Puerto Rico','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '193','country' => 'Qatar','currency' => 'Qatari Rial','code' => 'QAR','symbol' => NULL),
            array('id' => '194','country' => 'Réunion','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '195','country' => 'Romania','currency' => 'Romanian Leu','code' => 'RON','symbol' => 'lei'),
            array('id' => '196','country' => 'Russian Federation','currency' => 'Russian Ruble','code' => 'RUB','symbol' => '₽'),
            array('id' => '197','country' => 'Rwanda','currency' => 'Rwanda Franc','code' => 'RWF','symbol' => NULL),
            array('id' => '198','country' => 'Saint Barthélemy','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '199','country' => 'Saint Helena, Ascension And Tristan Da Cunha','currency' => 'Saint Helena Pound','code' => 'SHP','symbol' => NULL),
            array('id' => '200','country' => 'Saint Kitts And Nevis','currency' => 'East Caribbean Dollar','code' => 'XCD','symbol' => NULL),
            array('id' => '201','country' => 'Saint Lucia','currency' => 'East Caribbean Dollar','code' => 'XCD','symbol' => NULL),
            array('id' => '202','country' => 'Saint Martin (French Part)','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '203','country' => 'Saint Pierre And Miquelon','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '204','country' => 'Saint Vincent And The Grenadines','currency' => 'East Caribbean Dollar','code' => 'XCD','symbol' => NULL),
            array('id' => '205','country' => 'Samoa','currency' => 'Tala','code' => 'WST','symbol' => NULL),
            array('id' => '206','country' => 'San Marino','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '207','country' => 'Sao Tome And Principe','currency' => 'Dobra','code' => 'STN','symbol' => NULL),
            array('id' => '208','country' => 'Saudi Arabia','currency' => 'Saudi Riyal','code' => 'SAR','symbol' => '﷼'),
            array('id' => '209','country' => 'Senegal','currency' => 'CFA Franc BCEAO','code' => 'XOF','symbol' => NULL),
            array('id' => '210','country' => 'Serbia','currency' => 'Serbian Dinar','code' => 'RSD','symbol' => NULL),
            array('id' => '211','country' => 'Seychelles','currency' => 'Seychelles Rupee','code' => 'SCR','symbol' => NULL),
            array('id' => '212','country' => 'Sierra Leone','currency' => 'Leone','code' => 'SLL','symbol' => NULL),
            array('id' => '213','country' => 'Singapore','currency' => 'Singapore Dollar','code' => 'SGD','symbol' => '$'),
            array('id' => '214','country' => 'Sint Maarten (Dutch Part)','currency' => 'Netherlands Antillean Guilder','code' => 'ANG','symbol' => NULL),
            array('id' => '215','country' => 'Sistema Unitario De Compensacion Regional De Pagos "sucre"""','currency' => 'Sucre','code' => 'XSU','symbol' => NULL),
            array('id' => '216','country' => 'Slovakia','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '217','country' => 'Slovenia','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '218','country' => 'Solomon Islands','currency' => 'Solomon Islands Dollar','code' => 'SBD','symbol' => NULL),
            array('id' => '219','country' => 'Somalia','currency' => 'Somali Shilling','code' => 'SOS','symbol' => NULL),
            array('id' => '220','country' => 'South Africa','currency' => 'Rand','code' => 'ZAR','symbol' => 'R'),
            array('id' => '221','country' => 'South Sudan','currency' => 'South Sudanese Pound','code' => 'SSP','symbol' => NULL),
            array('id' => '222','country' => 'Spain','currency' => 'Euro','code' => 'EUR','symbol' => '€'),
            array('id' => '223','country' => 'Sri Lanka','currency' => 'Sri Lanka Rupee','code' => 'LKR','symbol' => 'Rs'),
            array('id' => '224','country' => 'Sudan (the)','currency' => 'Sudanese Pound','code' => 'SDG','symbol' => NULL),
            array('id' => '225','country' => 'Suriname','currency' => 'Surinam Dollar','code' => 'SRD','symbol' => NULL),
            array('id' => '226','country' => 'Svalbard And Jan Mayen','currency' => 'Norwegian Krone','code' => 'NOK','symbol' => NULL),
            array('id' => '227','country' => 'Sweden','currency' => 'Swedish Krona','code' => 'SEK','symbol' => 'kr'),
            array('id' => '228','country' => 'Switzerland','currency' => 'Swiss Franc','code' => 'CHF','symbol' => NULL),
            array('id' => '229','country' => 'Switzerland','currency' => 'WIR Euro','code' => 'CHE','symbol' => NULL),
            array('id' => '230','country' => 'Switzerland','currency' => 'WIR Franc','code' => 'CHW','symbol' => NULL),
            array('id' => '231','country' => 'Syrian Arab Republic','currency' => 'Syrian Pound','code' => 'SYP','symbol' => NULL),
            array('id' => '232','country' => 'Taiwan','currency' => 'New Taiwan Dollar','code' => 'TWD','symbol' => NULL),
            array('id' => '233','country' => 'Tajikistan','currency' => 'Somoni','code' => 'TJS','symbol' => NULL),
            array('id' => '234','country' => 'Tanzania, United Republic Of','currency' => 'Tanzanian Shilling','code' => 'TZS','symbol' => NULL),
            array('id' => '235','country' => 'Thailand','currency' => 'Baht','code' => 'THB','symbol' => '฿'),
            array('id' => '236','country' => 'Timor-leste','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '237','country' => 'Togo','currency' => 'CFA Franc BCEAO','code' => 'XOF','symbol' => NULL),
            array('id' => '238','country' => 'Tokelau','currency' => 'New Zealand Dollar','code' => 'NZD','symbol' => '$'),
            array('id' => '239','country' => 'Tonga','currency' => 'Pa’anga','code' => 'TOP','symbol' => NULL),
            array('id' => '240','country' => 'Trinidad And Tobago','currency' => 'Trinidad and Tobago Dollar','code' => 'TTD','symbol' => NULL),
            array('id' => '241','country' => 'Tunisia','currency' => 'Tunisian Dinar','code' => 'TND','symbol' => NULL),
            array('id' => '242','country' => 'Turkey','currency' => 'Turkish Lira','code' => 'TRY','symbol' => '₺'),
            array('id' => '243','country' => 'Turkmenistan','currency' => 'Turkmenistan New Manat','code' => 'TMT','symbol' => NULL),
            array('id' => '244','country' => 'Turks And Caicos Islands','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '245','country' => 'Tuvalu','currency' => 'Australian Dollar','code' => 'AUD','symbol' => NULL),
            array('id' => '246','country' => 'Uganda','currency' => 'Uganda Shilling','code' => 'UGX','symbol' => NULL),
            array('id' => '247','country' => 'Ukraine','currency' => 'Hryvnia','code' => 'UAH','symbol' => '₴'),
            array('id' => '248','country' => 'United Arab Emirates','currency' => 'UAE Dirham','code' => 'AED','symbol' => 'د.إ'),
            array('id' => '249','country' => 'United Kingdom Of Great Britain And Northern Ireland','currency' => 'Pound Sterling','code' => 'GBP','symbol' => '£'),
            array('id' => '250','country' => 'United States Minor Outlying Islands','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '251','country' => 'United States Of America','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '252','country' => 'United States Of America','currency' => 'US Dollar (Next day)','code' => 'USN','symbol' => NULL),
            array('id' => '253','country' => 'Uruguay','currency' => 'Peso Uruguayo','code' => 'UYU','symbol' => NULL),
            array('id' => '254','country' => 'Uruguay','currency' => 'Uruguay Peso en Unidades Indexadas (UI)','code' => 'UYI','symbol' => NULL),
            array('id' => '255','country' => 'Uruguay','currency' => 'Unidad Previsional','code' => 'UYW','symbol' => NULL),
            array('id' => '256','country' => 'Uzbekistan','currency' => 'Uzbekistan Sum','code' => 'UZS','symbol' => NULL),
            array('id' => '257','country' => 'Vanuatu','currency' => 'Vatu','code' => 'VUV','symbol' => NULL),
            array('id' => '258','country' => 'Venezuela','currency' => 'Bolívar Soberano','code' => 'VES','symbol' => NULL),
            array('id' => '259','country' => 'Vietnam','currency' => 'Dong','code' => 'VND','symbol' => '₫'),
            array('id' => '260','country' => 'Virgin Islands (British)','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '261','country' => 'Virgin Islands (U.S.)','currency' => 'US Dollar','code' => 'USD','symbol' => '$'),
            array('id' => '262','country' => 'Wallis And Futuna','currency' => 'CFP Franc','code' => 'XPF','symbol' => NULL),
            array('id' => '263','country' => 'Western Sahara','currency' => 'Moroccan Dirham','code' => 'MAD','symbol' => NULL),
            array('id' => '264','country' => 'Yemen','currency' => 'Yemeni Rial','code' => 'YER','symbol' => NULL),
            array('id' => '265','country' => 'Zambia','currency' => 'Zambian Kwacha','code' => 'ZMW','symbol' => NULL),
            array('id' => '266','country' => 'Zimbabwe','currency' => 'Zimbabwe Dollar','code' => 'ZWL','symbol' => NULL)
        );

        DB::table('currencies')->upsert($currencies, ['id'], ['country', 'currency','code','symbol']);

    }
}
